config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get 'posts/:id' => "posts#post", as: :post

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  Post = Struct.new(:permalink, :image_name, :content)

  def post
    @posts = []
    @posts << Post.new("waffles-are-okay", "waffles.jpg", "A waffle is a leavened batter or dough cooked between two plates, patterned to give a characteristic size, shape and surface impression. There are many variations based on the type of waffle iron and recipe used. Waffles are eaten throughout the world, particularly in Belgium, France, Netherlands, Germany, Poland, Hungary, Scandinavia, United States, with over a dozen regional varieties in Belgium alone.[1]")
    @posts << Post.new("pancakes-are-better", "pancakes.jpg", "A pancake is a flat cake, often thin, and round, prepared from a starch-based batter and cooked on a hot surface such as a griddle or frying pan. In Britain, pancakes are often unleavened, and resemble a crêpe. In North America, a raising agent is used (typically baking powder). The North American pancake is similar to a Scotch pancake or drop scone.

    They may be served at any time with a variety of toppings or fillings including jam, fruit, syrup, chocolate chips, or meat. In America, they are typically considered to be a breakfast food. In Britain and the Commonwealth, they are associated with Shrove Tuesday, commonly known as Pancake Day, when perishable ingredients had to be used up before the fasting period of Lent began.

    Archaeological evidence suggests that pancakes are probably the earliest and most widespread cereal food eaten in prehistoric societies.[1] The pancake's shape and structure varies worldwide. A crêpe is a thin Breton pancake cooked on one or both sides in a special pan or crepe maker to achieve a lacelike network of fine bubbles. A well-known variation originating in Southeast Europe is Palačinke, a thin moist pancake fried on both sides and filled with jam, cheese cream, chocolate, or ground walnuts, but many other fillings, both sweet or savory, can also be used.")
    @posts << Post.new("bacon-is-good", "bacon.jpg", "Bacon is a meat product prepared from a pig and usually cured.[1][2] It is first cured using large quantities of salt,[2] either in a brine or in a dry packing; the result is fresh bacon (also known as green bacon).[3] Fresh bacon may then be further dried for weeks or months in cold air, or it may be boiled or smoked.[1] Fresh and dried bacon is typically cooked before eating. Boiled bacon is ready to eat, as is some smoked bacon, but may be cooked further before eating.")
    @posts << Post.new("fried-chicken-is-best", "chicken.jpg", "Fried chicken (also referred to as Southern fried chicken) is a dish consisting of chicken pieces usually from broiler chickens which have been floured or battered and then pan-fried, deep fried, or pressure fried. The breading adds a crisp coating or crust to the exterior. What separates fried chicken from other fried forms of chicken is that generally the chicken is cut at the joints and the bones and skin are left intact. Crisp well-seasoned skin, rendered of excess fat, is a hallmark of well made fried chicken.")

    @post = @posts.find {|p| p.permalink == params[:id]}

  end

  def index
     @posts = []
     @posts << Post.new("waffles-are-okay", "waffles.jpg", "A waffle is a leavened batter or dough cooked between two plates, patterned to give a characteristic size, shape and surface impression. There are many variations based on the type of waffle iron and recipe used. Waffles are eaten throughout the world, particularly in Belgium, France, Netherlands, Germany, Poland, Hungary, Scandinavia, United States, with over a dozen regional varieties in Belgium alone.[1]")
     @posts << Post.new("pancakes-are-better", "pancakes.jpg", "A pancake is a flat cake, often thin, and round, prepared from a starch-based batter and cooked on a hot surface such as a griddle or frying pan. In Britain, pancakes are often unleavened, and resemble a crêpe. In North America, a raising agent is used (typically baking powder). The North American pancake is similar to a Scotch pancake or drop scone.

     They may be served at any time with a variety of toppings or fillings including jam, fruit, syrup, chocolate chips, or meat. In America, they are typically considered to be a breakfast food. In Britain and the Commonwealth, they are associated with Shrove Tuesday, commonly known as Pancake Day, when perishable ingredients had to be used up before the fasting period of Lent began.

     Archaeological evidence suggests that pancakes are probably the earliest and most widespread cereal food eaten in prehistoric societies.[1] The pancake's shape and structure varies worldwide. A crêpe is a thin Breton pancake cooked on one or both sides in a special pan or crepe maker to achieve a lacelike network of fine bubbles. A well-known variation originating in Southeast Europe is Palačinke, a thin moist pancake fried on both sides and filled with jam, cheese cream, chocolate, or ground walnuts, but many other fillings, both sweet or savory, can also be used.")
     @posts << Post.new("bacon-is-good", "bacon.jpg", "Bacon is a meat product prepared from a pig and usually cured.[1][2] It is first cured using large quantities of salt,[2] either in a brine or in a dry packing; the result is fresh bacon (also known as green bacon).[3] Fresh bacon may then be further dried for weeks or months in cold air, or it may be boiled or smoked.[1] Fresh and dried bacon is typically cooked before eating. Boiled bacon is ready to eat, as is some smoked bacon, but may be cooked further before eating.")
     @posts << Post.new("fried-chicken-is-best", "chicken.jpg", "Fried chicken (also referred to as Southern fried chicken) is a dish consisting of chicken pieces usually from broiler chickens which have been floured or battered and then pan-fried, deep fried, or pressure fried. The breading adds a crisp coating or crust to the exterior. What separates fried chicken from other fried forms of chicken is that generally the chicken is cut at the joints and the bones and skin are left intact. Crisp well-seasoned skin, rendered of excess fat, is a hallmark of well made fried chicken.")

    @post = @posts.last

 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= @title %></title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

   <!-- Optional theme -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
   <%=stylesheet_link_tag "application" %>
   <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
   <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,600,400' rel='stylesheet' type='text/css'>
</head>

<body>
<header>
   <div class="overlay">

      <div class='row no-gutter'>
         <div class='col-md-6 hidden-sm text-center hidden-xs'>
            <p><%= link_to "Home", root_path %></p>
         </div>
         <div class='col-md-6 col-xs-12'>
            <ul class='list-unstyled list-inline text-center'>
               <li>About</li>
               <li>Search</li>
               <li><i class='glyphicon glyphicon-search'></i>
               </ul>
            </div>
            <h1 class='text-center'>Surf & Paddle Co.</h1>
            <h2 class='text-center'>An Ironyard Academy Est. Fall 2013</h2>

         </div>
      </header>

      <div class="container">

         <div class="row no-gutter">
            <div class="col-md-8 col-xs-12">

               <content-left>
                  <%=yield%>
               </content-left>
                  </div>

                  <content-right>
                     <div class="col-md-offset-1 col-md-3 col-xs-12">
                        <div class='right'>
                           <div class='imgoverlay'>
                              <%= image_tag("06403b4.jpg", :class => "img-responsive img-circle") %>
                           </div>
                           <h3 class='text-center'>Danny Sun</h3>
                           <ul class='list-unstyled list-inline text-center'>
                              <li>Twitter</li>
                              <li>Facebook</li>
                              <li>Instagram</li>
                           </ul>
                           <%= image_tag("yoga2.jpg", :class => "img-responsive") %>
                           <div class='hidden-xs'>
                              <h1>About Me</h1>
                              <p>Lorem ipsum dolor sit amet, vis vidisse docendi intellegam an, et per etiam iriure integre, ad vel zril vocent noluisse. Vide molestie disputando at quo, in adhuc minim eam. Iisque ponderum indoctum est at, aeque postea at has. Ius dicam inciderint cotidieque ex, cu harum essent convenire usu, rebum inani referrentur eam cu. Vel eu nihil volumus legendos.</p>
                           </div>
                           </div
                        </content-right>
                     </div>
                  </div>
               </div>
            </div>

               <footer>
                  <div class='row no-gutter'>
                     <h1 class='text-center'>More popular posts</h1>
                  </div>



                  <div class='row no-gutter'>
                     <%= render partial: "footer" %>
                  </div>

                  <div class='bottom'>
                     <div class='col-md-6 col-xs-12 text-center'>
                        <p>The Ironyard Copyright 2013. All Rights Reserved.</p>
                     </div>

                     <div class='col-md-6 col-xs-12 text-center'>
                        <ul class='list-unstyled list-inline'>
                           <li>Nav Item 1</li>
                           <li>Nav Item 2</li>
                           <li>Nav Item 3</li>
                           <li>Nav Item 4</li>
                        </div>
                     </div>
                  </footer>
               </body>
               </html>

app/views/posts/_footer.html.erb
<% @posts.reverse.each do |post| %>
   <div class='col-md-3 col-sm-4 col-xs-12'>
     <%= link_to post_path(post.permalink) do %>
      <div class="cage" style="background: url(<%= image_path post.image_name%>); background-position: 28%; background-size: 200%">
         <div class="overlay">
               <h1 class='text-right'>
                  <%= post.permalink.gsub("-", ' ').upcase%>
                </h1>
          </div>
      </div>
      <% end %>
   </div>
 <% end %>

app/views/posts/_post.html.erb
<h1><%=  @post.permalink.gsub("-", ' ') %></h1>
</br>
<%= link_to post_path(@post.permalink) do %>
  <%= image_tag @post.image_name, :class => "img-responsive" %>
<% end %>
</br>
<p><%=  @post.content %></p>

app/views/posts/index.html.erb
<%= render partial: 'post' %>

app/views/posts/post.html.erb
<%= render partial: 'post' %>